# Generated by Django 2.1.11 on 2019-11-19 00:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lmn', '0002_userprofile'),
        ('lmn', '0002_note_photo'),
    ]

    operations = [
    ]
