# Generated by Django 2.1.11 on 2019-11-15 23:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lmn', '0002_userprofile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='user',
            new_name='username',
        ),
    ]
