# Generated by Django 2.1.11 on 2019-11-19 15:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lmn', '0003_merge_20191118_1845'),
        ('lmn', '0004_auto_20191118_2018'),
    ]

    operations = [
    ]
