# Generated by Django 2.1.11 on 2019-11-20 03:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lmn', '0005_merge_20191119_0952'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='note',
            name='photo',
        ),
    ]
